const OPER_PICKED = 'OPER_PICKED';
const CLEAR_PICKED = 'CLEAR_PICKED';
const EMPTY_PICKED = 'EMPTY_PICKED';
const NUMBER_PICKED = 'NUMBER_PICKED';
const EQUAL_PICKED = 'EQUAL_PICKED';

export {
    OPER_PICKED,
    CLEAR_PICKED,
    EMPTY_PICKED,
    NUMBER_PICKED,
    EQUAL_PICKED
};