const OPER_PICKED = 'OPER_PICKED';
const CLEAR_PICKED = 'CLEAR_PICKED';
const EMPTY_PICKED = 'EMPTY_PICKED';
const NUMBER_PICKED = 'NUMBER_PICKED';
const EQUAL_PICKED = 'EQUAL_PICKED';
const CLEAR_STYLE = 'CLEAR_STYLE';
const EMPTY_STYLE = 'EMPTY_STYLE';
const OPER_STYLE = 'OPER_STYLE';
const NUMBER_STYLE = 'NUMBER_STYLE';


export {
    OPER_PICKED,
    CLEAR_PICKED,
    EMPTY_PICKED,
    NUMBER_PICKED,
    EQUAL_PICKED,
    CLEAR_STYLE,
    EMPTY_STYLE,
    OPER_STYLE,
    NUMBER_STYLE,
};