const actions = {
    OPER_PICKED: 'OPER_PICKED',
    CLEAR_PICKED: 'CLEAR_PICKED',
    EMPTY_PICKED: 'EMPTY_PICKED',
    NUMBER_PICKED: 'NUMBER_PICKED',
    EQUAL_PICKED: 'EQUAL_PICKED',
    CLEAR_STYLE: 'CLEAR_STYLE',
    EMPTY_STYLE: 'EMPTY_STYLE',
    OPER_STYLE: 'OPER_STYLE',
    NUMBER_STYLE: 'NUMBER_STYLE',
    DISPLAY_BOX: 'DISPLAY_BOX',
}

export {
    actions
}