name: Test coverall

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: npm install, Coverage from Jest
      run: 
        npm install
        npm run coverage
    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with: github-token: ${{ secrets.github_token }}
